/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 20, 2019 at 11:33:29 AM Greenwich Mean Time
* Operating System: Version 12.1.1 (Build 16C5050a)
* Image Source: /System/Library/ControlCenter/Bundles/AudioModule.bundle/AudioModule
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <ControlCenterUIKit/AudioModule-Structs.h>
#import <ControlCenterUIKit/CCUIModuleSliderView.h>

@class UIView, UIImpactFeedbackGenerator;

@interface CCUIVolumeSliderView : CCUIModuleSliderView {

	BOOL _euDevice;
	float _euVolumeLimit;
	BOOL _euVolumeLimitEnforced;
	UIView* _orangeValueView;
	BOOL _didAcknowledgeThreshold;
	BOOL _didHitThreshold;
	UIImpactFeedbackGenerator* _impactFeedbackGenerator;

}
-(void)_initializeEUVolumeLimits;
-(void)_EUVolumeLimitChanged:(id)arg1 ;
-(void)_EUVolumeEnforcementChanged:(id)arg1 ;
-(void)resetThresholdAcknowledgment;
-(void)_serverConnectionDied:(id)arg1 ;
-(float)_limitedVolumeValue;
-(void)_handleValueChangeGestureRecognizer:(id)arg1 ;
-(void)_layoutContinuousValueViewForValue:(float)arg1 ;
-(float)_valueForPanGestureRecognizer:(id)arg1 withAbsoluteReference:(BOOL)arg2 ;
-(void)setContinuousSliderCornerRadius:(double)arg1 ;
-(void)setNumberOfSteps:(unsigned long long)arg1 ;
-(void)_unregisterForAVSystemControllerNotifications;
-(void)_registerForAVSystemControllerNotifications;
-(id)initWithFrame:(CGRect)arg1 ;
@end

