/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, March 20, 2019 at 11:33:29 AM Greenwich Mean Time
* Operating System: Version 12.1.1 (Build 16C5050a)
* Image Source: /System/Library/ControlCenter/Bundles/AudioModule.bundle/AudioModule
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CCUIContentModule <NSObject>
@property (nonatomic,readonly) UIViewController*<CCUIContentModuleContentViewController> contentViewController; 
@property (nonatomic,readonly) UIViewController*<CCUIContentModuleBackgroundViewController> backgroundViewController; 
@optional
-(void)setContentModuleContext:(id)arg1;
-(UIViewController*<CCUIContentModuleBackgroundViewController>)backgroundViewController;

@required
-(UIViewController*<CCUIContentModuleContentViewController>)contentViewController;

@end

